### ISSUE TITLE
Testing and TDD

### ISSUE THREAD

**Issue by adhicoder** [MadhavM-117/pacmanJS#10]
I'll set up a framework with Mocha/Jasmine and start off a couple of tests.

Let's try to follow these practices:
* Testing out the logic of each code segment with unit tests
* TDD, sooner rather than later
* Testing the canvas drawing functions with [Canteen](https://github.com/platfora/Canteen) and [Rabbit](https://github.com/cristiingineru/rabbit/) that will use a reference catalog to test image drawing on canvas. (Do this only for quality improvement purposes later - Don't waste time drawing detailed pictures for catalogs)

A good intro to TDD with canvases in JS:
https://stackoverflow.com/questions/4406864/html-canvas-unit-testing

**Comment by adhicoder** [comment]
Some resources to get you started with TDD:
- [TDD](https://medium.com/javascript-scene/tdd-the-rite-way-53c9b46f45e3) the "RITE" way
- [Mocha](https://mochajs.org/) for unit tests
- [Chai](https://www.chaijs.com/) for assertions
- [Testdouble](https://github.com/testdouble/testdouble.js#api) for mocking

**Comment by MadhavM-117** [comment]
As mentioned in your PR #15 , we should also some way of displaying test coverage. 
GitHub Actions and CI are free, I think, so perhaps we should take a look at that?

**Comment by MadhavM-117** [comment]
Also, by coverage, you meant for unit tests, right?

**Comment by adhicoder** [comment]
Yea, I mean for unit tests. I've done coverage in the past with a library called nyc and it's pretty simple to use. But if you think the other options are worth a try, I'm game.

**Comment by MadhavM-117** [comment]
Sure, I've never set up anything like that before, so I have no real preferences. 

If you can set it up, that'd be great! When will the coverage be updated? On every commit to master?
