### ISSUE TITLE
Drawing the sprites

### ISSUE THREAD

**Issue by MadhavM-117** [MadhavM-117/pacmanJS#2]

**Comment by MadhavM-117** [comment]
I think every sprite (besides the walls) should have their own class, that will have it's own methods to: 
- draw
- detectCollisions
- detectDestruction
as well as the ability to track its own state. 

We could perhaps have some sort of base class that we can use as in interface, or inherit. Thoughts?

**Comment by adhicoder** [comment]
Yes, I was thinking along the same lines. We would also need properties like the current coordinates to detect collision. We'll think about whether to inherit or create separate classes. We can refactor later if needed.
